Allow customisable auth path for all other auth methods
zendesk/vault-ruby pull request #1
Opened 2019-04-04 19:00 UTC by adammw

Clone of https://github.com/zendesk/vault-ruby/pull/200 upstream.

/cc @zendesk/compute @zendesk/config

2019-04-04 19:05 UTC, hgokavarapuz approved these changes

2019-04-04 19:50 UTC, grosser commented on lib/vault/api/auth.rb
> +    def token(new_token, path = 'token')
```suggestion
    def token(new_token, path: 'token')
```

2019-04-04 19:51 UTC, grosser commented on lib/vault/api/auth.rb
> +    def app_id(app_id, user_id, options = {}, path = 'app-id')
♋️

2019-04-04 19:51 UTC, grosser commented on lib/vault/api/auth.rb
> +    def approle(role_id, secret_id=nil, path='approle')
👁 ♋️

2019-04-04 19:52 UTC, grosser requested changes
keyword args :D

2019-04-04 20:07 UTC, adammw commented
I mean, the library isn't using keyword args anywhere else...

2019-04-04 20:08 UTC, grosser commented
does not hurt to start ... at least don't put optional arguments after options hash

2019-04-04 23:37 UTC, grosser approved these changes

2019-04-04 23:38 UTC, grosser commented
tests would be good ... but idk what the testing infrastructure looks like here 🤷‍♂️

2019-04-05 17:50 UTC, adammw commented
so ldap and tls options are completely untested in the integration tests, but added tests for the other ones.

2019-04-05 17:54 UTC, grosser commented
they all look very similar, can they get moved to a single generic auth method ?

2019-04-05 17:54 UTC, grosser approved these changes

2019-04-05 17:54 UTC, adammw commented
:shurg:

don't want to deal too much more with this gem right now. this does what i need.

2019-04-05 17:55 UTC, merged